create table tasks (
	id bigint generated by default as identity primary key,
	title varchar(160) not null,
	completed boolean not null default false,
	created_at timestamp with time zone not null
);

insert into tasks (title, completed, created_at)
values
	('Run the stack through Nginx', false, current_timestamp),
	('Scale the Java API service', false, current_timestamp);
